<?php
if (!defined('ABSPATH')) {
    exit;
}

global $product;
if (!$product instanceof WC_Product) {
    $product = wc_get_product(get_the_ID());
}
if (!$product) {
    status_header(404);
    return;
}

$value_or_na = static function ($value) {
    $value = trim(wp_strip_all_tags((string) $value));
    return $value !== '' ? $value : 'N/A';
};
$category_names = wp_get_post_terms($product->get_id(), 'product_cat', array('fields' => 'names'));
$categories = !is_wp_error($category_names) && $category_names
    ? implode(', ', $category_names)
    : 'N/A';
$media_url = $product->get_meta('_iristick_media_url');
$media_type = $product->get_meta('_iristick_media_type');
$features = (array) $product->get_meta('_iristick_features');
$specs = (array) $product->get_meta('_iristick_specs');
$documents = (array) $product->get_meta('_iristick_documents');
$faqs = (array) $product->get_meta('_iristick_faq');
?>
<!doctype html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo('charset'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=block">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Manrope:wght@300;400;500;600;700;800&family=Plus+Jakarta+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,400;1,600;1,700&display=swap">
    <link rel="stylesheet" href="<?php echo esc_url(IRISTICK_STATIC_URI . '/static/base.css?v=' . IRISTICK_STATIC_VERSION); ?>">
    <link rel="stylesheet" href="<?php echo esc_url(IRISTICK_STATIC_URI . '/static/_app/immutable/assets/button.Cnk_Ow-q.css?v=' . IRISTICK_STATIC_VERSION); ?>">
    <link rel="stylesheet" href="<?php echo esc_url(IRISTICK_STATIC_URI . '/static/_app/immutable/assets/0.D44dWdpH.css?v=' . IRISTICK_STATIC_VERSION); ?>">
    <link rel="stylesheet" href="<?php echo esc_url(IRISTICK_STATIC_URI . '/assets/css/responsive.css?v=' . IRISTICK_STATIC_VERSION); ?>">
    <link rel="stylesheet" href="<?php echo esc_url(IRISTICK_STATIC_URI . '/assets/css/woocommerce-product.css?v=' . IRISTICK_STATIC_VERSION); ?>">

    <?php
    ob_start();
    wp_head();
    $product_head = ob_get_clean();
    $product_title = '<title>' . esc_html($product->get_name() . ' | Iristick Việt Nam') . '</title>';
    if (preg_match('#<title\b[^>]*>.*?</title>#is', $product_head)) {
        $product_head = preg_replace('#<title\b[^>]*>.*?</title>#is', $product_title, $product_head, 1);
    } else {
        $product_head = $product_title . $product_head;
    }
    echo $product_head; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by wp_head().
    ?>
</head>
<body <?php body_class('iristick-product-page'); ?>>
<?php wp_body_open(); ?>
<?php echo iristick_site_header_html(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>

<main class="iristick-product-shell">
    <article class="iristick-classic-product">
        <div class="iristick-product-media">
            <?php if ($media_type === 'video' && $media_url && $media_url !== 'N/A') : ?>
                <video autoplay muted loop playsinline controls><source src="<?php echo esc_url($media_url); ?>" type="video/mp4"></video>
            <?php elseif ($media_type === 'image' && $media_url && $media_url !== 'N/A') : ?>
                <img src="<?php echo esc_url($media_url); ?>" alt="<?php echo esc_attr($product->get_name()); ?>">
            <?php elseif ($product->get_image_id()) : ?>
                <?php echo wp_kses_post($product->get_image('full')); ?>
            <?php else : ?>
                <div class="iristick-product-placeholder"><span>👓</span><small>Chưa có hình ảnh</small></div>
            <?php endif; ?>
        </div>

        <section class="iristick-classic-summary">
            <div class="iristick-product-title-row">
                <h1><?php echo esc_html($product->get_name()); ?></h1>
                <span>Chính hãng</span>
            </div>
            <div class="iristick-product-lead"><?php echo esc_html($value_or_na($product->get_short_description())); ?></div>
            <div class="iristick-product-price">
                <?php 
                if ($product->get_price_html()) {
                    echo wp_kses_post($product->get_price_html());
                } elseif ($product->get_price()) {
                    echo number_format((float) $product->get_price(), 0, ',', '.') . '&nbsp;₫';
                } else {
                    echo 'Liên hệ báo giá';
                }
                ?>
            </div>
            
            <?php if ($product->is_purchasable()) : ?>
                <div class="iristick-purchase-actions">
                    <a class="iristick-zalo-button" href="https://zalo.me/0917834532" target="_blank" rel="noopener noreferrer">Tư vấn qua Zalo</a>
                    <?php woocommerce_template_single_add_to_cart(); ?>
                </div>
            <?php else : ?>
                <div class="iristick-purchase-actions">
                    <a class="iristick-zalo-button" href="https://zalo.me/0917834532" target="_blank" rel="noopener noreferrer">Tư vấn qua Zalo</a>
                    <a class="iristick-contact-product" href="<?php echo esc_url(home_url('/book-demo/')); ?>">Đặt lịch Demo</a>
                </div>
            <?php endif; ?>

            <form class="iristick-phone-consultation" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" method="post">
                <input type="hidden" name="action" value="iristick_phone_consultation">
                <input type="hidden" name="product_id" value="<?php echo absint($product->get_id()); ?>">
                <?php wp_nonce_field('iristick_phone_consultation', 'iristick_phone_nonce'); ?>
                <strong><span aria-hidden="true">☎</span> Để lại số điện thoại, chúng tôi sẽ gọi lại tư vấn miễn phí!</strong>
                <div class="iristick-phone-row">
                    <label class="screen-reader-text" for="iristick-consultation-phone">Số điện thoại</label>
                    <input id="iristick-consultation-phone" type="tel" name="phone" inputmode="numeric" autocomplete="tel" placeholder="Ví dụ: 0917834532" pattern="(?:\+84|0)(?:3|5|7|8|9)[0-9]{8}" minlength="10" maxlength="12" title="Nhập số di động Việt Nam, ví dụ 0917834532 hoặc +84917834532" required>
                    <button type="submit">Gửi đi</button>
                </div>
                <?php if (isset($_GET['phone_status'])) : ?>
                    <p class="iristick-phone-status"><?php echo $_GET['phone_status'] === 'success' ? 'Đã gửi yêu cầu. Chúng tôi sẽ liên hệ với bạn sớm!' : 'Chưa thể gửi yêu cầu. Vui lòng kiểm tra lại số điện thoại.'; ?></p>
                <?php endif; ?>
            </form>
        </section>

        <section class="iristick-product-accordions">
            <details open>
                <summary>Tính năng chính</summary>
                <div class="iristick-accordion-content">
                    <?php if ($features) : ?>
                        <div class="iristick-feature-grid">
                            <?php foreach ($features as $label => $feature) : ?>
                                <div>
                                    <strong><?php echo esc_html(is_string($label) && !is_numeric($label) ? $label : $feature); ?></strong>
                                    <?php if (is_string($label) && !is_numeric($label) && $feature !== 'N/A') : ?>
                                        <p><?php echo esc_html($feature); ?></p>
                                    <?php endif; ?>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    <?php else : ?>
                        <p><?php echo esc_html($value_or_na($product->get_description())); ?></p>
                    <?php endif; ?>
                </div>
            </details>
            <details open>
                <summary>Phụ kiện và thông số kỹ thuật</summary>
                <div class="iristick-accordion-content iristick-spec-grid">
                    <div><strong>Mã sản phẩm (SKU)</strong><p><?php echo esc_html($value_or_na($product->get_sku())); ?></p></div>
                    <div><strong>Danh mục</strong><p><?php echo esc_html($categories); ?></p></div>
                    <div><strong>Tình trạng hàng</strong><p><?php echo esc_html($product->is_in_stock() ? 'Còn hàng sẵn sàng giao' : 'Liên hệ đặt trước'); ?></p></div>
                    <?php foreach ($specs as $label => $value) : ?>
                        <?php if ($value && $value !== 'N/A') : ?>
                            <div><strong><?php echo esc_html($label); ?></strong><p><?php echo esc_html($value); ?></p></div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <?php foreach ($product->get_attributes() as $attribute) : ?>
                        <div><strong><?php echo esc_html(wc_attribute_label($attribute->get_name())); ?></strong><p><?php echo esc_html(implode(', ', $attribute->get_options()) ?: 'N/A'); ?></p></div>
                    <?php endforeach; ?>
                </div>
            </details>
            <?php if ($documents && !empty(array_filter($documents, function ($v) { return $v !== 'N/A'; }))) : ?>
                <details>
                    <summary>Tài liệu & Datasheet tải về</summary>
                    <div class="iristick-accordion-content">
                        <ul>
                            <?php foreach ($documents as $label => $url) : ?>
                                <?php if ($url !== 'N/A' && $url !== '') : ?>
                                    <li><a href="<?php echo esc_url($url); ?>" target="_blank" rel="noopener">📄 <?php echo esc_html($label); ?></a></li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </details>
            <?php endif; ?>
            <?php if ($faqs && !empty($faqs)) : ?>
                <details>
                    <summary>Câu hỏi thường gặp (FAQ)</summary>
                    <div class="iristick-accordion-content">
                        <?php foreach ($faqs as $faq) : ?>
                            <?php if (!empty($faq['question']) && $faq['question'] !== 'N/A') : ?>
                                <h4><?php echo esc_html($faq['question']); ?></h4>
                                <p><?php echo esc_html(isset($faq['answer']) ? $faq['answer'] : 'N/A'); ?></p>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                </details>
            <?php endif; ?>
        </section>
    </article>
</main>

<?php echo iristick_site_footer_html(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
<?php wp_footer(); ?>
</body>
</html>
