<?php
if (!defined('ABSPATH')) {
    exit;
}

global $product;
if (!$product instanceof WC_Product) {
    $product = wc_get_product(get_the_ID());
}
if (!$product) {
    status_header(404);
    return;
}

$value_or_na = static function ($value) {
    $value = trim(wp_strip_all_tags((string) $value));
    return $value !== '' ? $value : 'N/A';
};
$category_names = wp_get_post_terms($product->get_id(), 'product_cat', array('fields' => 'names'));
$categories = !is_wp_error($category_names) && $category_names
    ? implode(', ', $category_names)
    : 'N/A';
$media_url = $product->get_meta('_iristick_media_url');
$media_type = $product->get_meta('_iristick_media_type');
$features = (array) $product->get_meta('_iristick_features');
$specs = (array) $product->get_meta('_iristick_specs');
$documents = (array) $product->get_meta('_iristick_documents');
$faqs = (array) $product->get_meta('_iristick_faq');
?>
<!doctype html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo('charset'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php
    ob_start();
    wp_head();
    $product_head = ob_get_clean();
    $product_title = '<title>' . esc_html($product->get_name() . ' | Iristick Việt Nam') . '</title>';
    if (preg_match('#<title\b[^>]*>.*?</title>#is', $product_head)) {
        $product_head = preg_replace('#<title\b[^>]*>.*?</title>#is', $product_title, $product_head, 1);
    } else {
        $product_head = $product_title . $product_head;
    }
    echo $product_head; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by wp_head().
    ?>
</head>
<body <?php body_class('iristick-product-page'); ?>>
<?php wp_body_open(); ?>
<header class="iristick-store-header">
    <a class="iristick-store-logo" href="<?php echo esc_url(home_url('/')); ?>">
        <img src="<?php echo esc_url(IRISTICK_STATIC_URI . '/assets/images/iristick-logo.webp'); ?>" alt="Iristick Việt Nam">
    </a>
    <nav aria-label="Điều hướng chính">
        <details>
            <summary>Sản phẩm</summary>
            <div class="iristick-store-products">
                <?php foreach (wc_get_products(array('status' => 'publish', 'limit' => -1)) as $menu_product) : ?>
                    <a href="<?php echo esc_url($menu_product->get_permalink()); ?>">
                        <strong><?php echo esc_html($menu_product->get_name()); ?></strong>
                        <small><?php echo esc_html($value_or_na($menu_product->get_short_description())); ?></small>
                    </a>
                <?php endforeach; ?>
            </div>
        </details>
        <a href="<?php echo esc_url(home_url('/blog/news/')); ?>">Tài nguyên</a>
        <a href="<?php echo esc_url(home_url('/pricing/')); ?>">Bảng giá</a>
        <a href="<?php echo esc_url(home_url('/book-demo/')); ?>">Đặt lịch demo</a>
    </nav>
</header>

<main class="iristick-product-shell">
    <article class="iristick-classic-product">
        <div class="iristick-product-media">
            <?php if ($media_type === 'video' && $media_url && $media_url !== 'N/A') : ?>
                <video autoplay muted loop playsinline controls><source src="<?php echo esc_url($media_url); ?>" type="video/mp4"></video>
            <?php elseif ($media_type === 'image' && $media_url && $media_url !== 'N/A') : ?>
                <img src="<?php echo esc_url($media_url); ?>" alt="<?php echo esc_attr($product->get_name()); ?>">
            <?php elseif ($product->get_image_id()) : ?>
                <?php echo wp_kses_post($product->get_image('full')); ?>
            <?php else : ?>
                <div class="iristick-product-placeholder"><span>N/A</span><small>Chưa có hình ảnh</small></div>
            <?php endif; ?>
        </div>

        <section class="iristick-classic-summary">
            <div class="iristick-product-title-row">
                <h1><?php echo esc_html($product->get_name()); ?></h1>
                <span>MỚI</span>
            </div>
            <div class="iristick-product-lead"><?php echo esc_html($value_or_na($product->get_short_description())); ?></div>
            <div class="iristick-product-price"><?php echo $product->get_price_html() ? wp_kses_post($product->get_price_html()) : 'N/A'; ?></div>
            <?php if ($product->is_purchasable()) : ?>
                <div class="iristick-purchase-actions">
                    <a class="iristick-zalo-button" href="https://zalo.me/0917834532" target="_blank" rel="noopener noreferrer">Tư vấn qua Zalo</a>
                    <?php woocommerce_template_single_add_to_cart(); ?>
                </div>
            <?php else : ?>
                <a class="iristick-contact-product" href="<?php echo esc_url(home_url('/book-demo/')); ?>">Liên hệ với chúng tôi</a>
            <?php endif; ?>

            <form class="iristick-phone-consultation" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" method="post">
                <input type="hidden" name="action" value="iristick_phone_consultation">
                <input type="hidden" name="product_id" value="<?php echo absint($product->get_id()); ?>">
                <?php wp_nonce_field('iristick_phone_consultation', 'iristick_phone_nonce'); ?>
                <strong><span aria-hidden="true">☎</span> Để lại số điện thoại, chúng tôi sẽ gọi lại tư vấn miễn phí!</strong>
                <div class="iristick-phone-row">
                    <label class="screen-reader-text" for="iristick-consultation-phone">Số điện thoại</label>
                    <input id="iristick-consultation-phone" type="tel" name="phone" inputmode="numeric" autocomplete="tel" placeholder="Ví dụ: 0917834532" pattern="(?:\+84|0)(?:3|5|7|8|9)[0-9]{8}" minlength="10" maxlength="12" title="Nhập số di động Việt Nam, ví dụ 0917834532 hoặc +84917834532" required>
                    <button type="submit">Gửi đi</button>
                </div>
                <?php if (isset($_GET['phone_status'])) : ?>
                    <p class="iristick-phone-status"><?php echo $_GET['phone_status'] === 'success' ? 'Đã gửi yêu cầu. Chúng tôi sẽ liên hệ với bạn sớm!' : 'Chưa thể gửi yêu cầu. Vui lòng kiểm tra lại số điện thoại.'; ?></p>
                <?php endif; ?>
            </form>
        </section>

        <section class="iristick-product-accordions">
            <details>
                <summary>Tính năng chính</summary>
                <div class="iristick-accordion-content">
                    <?php if ($features) : ?><div class="iristick-feature-grid"><?php foreach ($features as $label => $feature) : ?><div><strong><?php echo esc_html(is_string($label) ? $label : $feature); ?></strong><?php if (is_string($label)) : ?><p><?php echo esc_html($feature ?: 'N/A'); ?></p><?php endif; ?></div><?php endforeach; ?></div><?php else : ?><p>N/A</p><?php endif; ?>
                </div>
            </details>
            <details open>
                <summary>Phụ kiện và thông số</summary>
                <div class="iristick-accordion-content iristick-spec-grid">
                    <div><strong>Mã sản phẩm</strong><p><?php echo esc_html($value_or_na($product->get_sku())); ?></p></div>
                    <div><strong>Danh mục</strong><p><?php echo esc_html($categories); ?></p></div>
                    <div><strong>Tình trạng</strong><p><?php echo esc_html($product->is_in_stock() ? 'Còn hàng' : 'Hết hàng'); ?></p></div>
                    <?php foreach ($specs as $label => $value) : ?>
                        <div><strong><?php echo esc_html($label); ?></strong><p><?php echo esc_html($value ?: 'N/A'); ?></p></div>
                    <?php endforeach; ?>
                    <?php foreach ($product->get_attributes() as $attribute) : ?>
                        <div><strong><?php echo esc_html(wc_attribute_label($attribute->get_name())); ?></strong><p><?php echo esc_html(implode(', ', $attribute->get_options()) ?: 'N/A'); ?></p></div>
                    <?php endforeach; ?>
                </div>
            </details>
            <details>
                <summary>Tài liệu</summary>
                <div class="iristick-accordion-content"><?php if ($documents) : ?><ul><?php foreach ($documents as $label => $url) : ?><li><?php if ($url !== 'N/A') : ?><a href="<?php echo esc_url($url); ?>" target="_blank" rel="noopener"><?php echo esc_html($label); ?></a><?php else : ?>N/A<?php endif; ?></li><?php endforeach; ?></ul><?php else : ?><p>N/A</p><?php endif; ?></div>
            </details>
            <details>
                <summary>FAQ</summary>
                <div class="iristick-accordion-content"><?php if ($faqs) : ?><?php foreach ($faqs as $faq) : ?><h4><?php echo esc_html(isset($faq['question']) ? $faq['question'] : 'N/A'); ?></h4><p><?php echo esc_html(isset($faq['answer']) ? $faq['answer'] : 'N/A'); ?></p><?php endforeach; ?><?php else : ?><p>N/A</p><?php endif; ?></div>
            </details>
        </section>
    </article>
</main>
<?php wp_footer(); ?>
</body>
</html>
